import json
from mcp.types import Tool, TextContent
from pydantic import BaseModel, Field
from typing import Optional
from ue5_mcp.client import EditorClient


class SpawnActorInput(BaseModel):
    class_path: str = Field(
        description="UE5 class path, e.g. '/Script/Engine.StaticMeshActor'")
    name: Optional[str] = Field(
        default=None,
        description="Optional actor name. Auto-generated by engine if omitted.")
    location: Optional[list[float]] = Field(
        default=None,
        description="[X, Y, Z] in world space, in centimeters.")
    rotation: Optional[list[float]] = Field(
        default=None,
        description="[Pitch, Yaw, Roll] in degrees.")


class DeleteActorInput(BaseModel):
    name: str = Field(description="Exact name of the actor to delete.")


TOOLS: list[Tool] = [
    Tool(
        name="list_actors",
        description=(
            "List all actors in the currently open UE5 level. "
            "Returns name, class, and engine ID for each actor."
        ),
        inputSchema={"type": "object", "properties": {}, "required": []},
    ),
    Tool(
        name="spawn_actor",
        description=(
            "Spawn a new actor in the current level. "
            "Returns the actual name the engine assigned, which may differ from the requested name."
        ),
        inputSchema=SpawnActorInput.model_json_schema(),
    ),
    Tool(
        name="delete_actor",
        description=(
            "Delete an actor from the current level by name. "
            "This action cannot be undone via this tool."
        ),
        inputSchema=DeleteActorInput.model_json_schema(),
    ),
]

TOOL_NAMES = {t.name for t in TOOLS}


async def handle(name: str, client: EditorClient, arguments: dict) -> list[TextContent]:
    if name == "list_actors":
        data = await client.get("/actors/list")
        return [TextContent(type="text", text=json.dumps(data, indent=2))]

    if name == "spawn_actor":
        inp = SpawnActorInput.model_validate(arguments)
        body: dict = {"class_path": inp.class_path}
        if inp.name:
            body["name"] = inp.name
        if inp.location:
            body["location"] = inp.location
        if inp.rotation:
            body["rotation"] = inp.rotation
        data = await client.post("/actors/spawn", body)
        return [TextContent(type="text", text=json.dumps(data, indent=2))]

    if name == "delete_actor":
        inp = DeleteActorInput.model_validate(arguments)
        data = await client.post("/actors/delete", {"name": inp.name})
        return [TextContent(type="text", text=json.dumps(data, indent=2))]

    raise ValueError(f"Unknown actor tool: {name}")
